markdown: kramdown
theme: minima

title: 2040FBDBIC
description: Chemo-informatics and computational drug design

minima:
  date_format: "%b %-d, %Y"
  
author:
  name: Hans De Winter
  email: "hans.dewinter@uantwerpen.be"

header_pages:
  - Topic_01
  - Topic_02
  - Topic_03
  - Topic_04
  - Topic_05

plugins:
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false
